### ISSUE TITLE
fastq screen config file

### ISSUE THREAD

**Issue by dvbrown** [WEHIGenomicsRnD/qc-pipe#1]
Please add the fastq_screen config file from **/stornext/Projects/score/Indexes/fastq_screen/FastQ_Screen_Genomes/fastq_screen.conf

to this repo

**Comment by mcmero** [comment]
As the repository is public, we want to keep WEHI-specific file-paths/settings separate. I've made a wiki page for this QC pipeline on the Genomics Lab with the fastq_screen.conf file content pointing to the shared score indexes.
