### ISSUE TITLE
Run with path to fastqs supplied in config.yaml

### ISSUE THREAD

**Issue by dvbrown** [WEHIGenomicsRnD/qc-pipe#2]
Its more convenient for me to have the path to the fastqs specified in the config.yaml.
Then I clone qc-pipe once and reuse. You would need the config file as an extra argument in the run command

**Comment by dvbrown** [comment]
When I use cell ranger mkfastq or bcl2fastq the filenames are emitted in bcl2fastq naming convention:

R010_CMO_CMO-1k_S1_L001_R1_001.fastq.gz
R010_LMO_LMO-1k_S2_L001_R1_001.fastq.gz

**Comment by mcmero** [comment]
I've added a parameter in the `config.yaml` file where you can specify a custom directory for fastqs you wish to process. 

The filename format is a little trickier. You can have the pipeline run bcl2fastq for you, which handles the naming convention. But this doesn't help with cell ranger. I'll add an option to run from the merge lanes step, which should address this (even if it's only a single lane, this will put the files into the right naming format).

**Comment by mcmero** [comment]
The latest commit adds the option to run from the merge lanes step, which will handle the bcl2fastq naming convention. In the config.yaml, you have to specify the input directory (`merge_from_dir`), the correct number of lanes, as well as include a sample sheet (there's a minimal example sample sheet under `.test/bcl_input/SampleSheet.csv`). In case of only one lane, it's a bit redundant, but you can treat the merge outputs as intermediary files and delete or zero them out after running the pipeline.

Happy to get any further suggestions/improvements 😃

**Comment by mcmero** [comment]
An update: a sample sheet is no longer required if running from the merge stage, which should simplify things.
